AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket with Static web site hosting  creation
  
Parameters:
  Key:
    Type: String
    
Resources:
  S3ReactBucket:
    Type: AWS::S3::Bucket
  
  
  {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:*",
        "s3-object-lambda:*"
      ],
      "Resource": "*"
    }
  ]
}