AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance creation

Parameters:
  EC2KeyPairName: # ec2-book-app-api-key (ключ ED25519 который я создал вручную для инстанца EC2, в AWS непредусмотренно создание из шаблона)
    Type: String

Resources:
  EC2BookAppApi:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0590f3a1742b17914  # AMI (Amazon Machine Image) - id OS (ubuntu ami-0590f3a1742b17914)
      InstanceType: t2.micro
      KeyName: !Ref EC2KeyPairName
      IamInstanceProfile: !Ref EC2InstanceProfileEC2InstanceRoleDynamoDB
      SecurityGroups:
        - !Ref SecurityGroupEC2BookAppApi
      UserData:
        Fn::Base64: |
          #!/bin/bash
          echo "------------------------------------- DOCKER INSTALL START -------------------------------------"
          dpkg --purge --force-all docker docker-engine docker.io containerd runc
          apt update
          apt install -y \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
          
          mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null\
          
          apt update
          apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          echo "------------------------------------- DOCKER INSTALL END -------------------------------------"
                                    
          sudo -u ubuntu -i << 'EOF'
          cd ~
          sudo docker --version > result.txt
          whoami > whoami.txt
          EOF
      Tags:
        - Key: Name
          Value: EC2BookAppApi
          
  SecurityGroupEC2BookAppApi:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroup_BookAppApi
      GroupDescription: Allowing SSH from everywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupEC2BookAppApi
          
  EC2InstanceRoleDynamoDB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: DynamoDBFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ListAndDescribe
                Effect: Allow
                Action:
                  - dynamodb:*
                  - dynamodb:DescribeReservedCapacity*
                  - dynamodb:DescribeLimits
                  - dynamodb:DescribeTimeToLive
                Resource: arn:aws:dynamodb:*

  EC2InstanceProfileEC2InstanceRoleDynamoDB:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRoleDynamoDB
