AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:
  EC2KeyPairName: # ec2-book-app-api-key (ключ который я создал вручную для инстанца EC2)
    Type: String

Resources:
  EC2BookAppApi:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0590f3a1742b17914  # AMI (Amazon Machine Image) - id OS (ubuntu ami-0590f3a1742b17914)
      InstanceType: t2.micro
      KeyName: !Ref EC2KeyPairName  
      SecurityGroups:
        - !Ref SecurityGroupEC2BookAppApi
      UserData:
        Fn::Base64: |
          #!/bin/bash
          
          
          sudo -u ubuntu -i << 'EOF'
          cd ~
          whoami > whoami.txt
          echo "Hello, world!" > kek.txt
          EOF
      Tags:
        - Key: Name
          Value: EC2BookAppApi
          
  SecurityGroupEC2BookAppApi:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroup_BookAppApi
      GroupDescription: Allowing SSH from everywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupEC2BookAppApi