AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:
  MyKeyPairName:
    Type: String

Resources:
  EC2BookAppApi:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0590f3a1742b17914  # id OS (ubuntu ami-0590f3a1742b17914)
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPairName  # talgat_ec2-booka-app-api (ключ который я создал при ручном создании другого инстанца EC2)
      SecurityGroups:
        - !Ref SecurityGroupEC2BookAppApi
      UserData:
        Fn::Base64: |
          #!/bin/bash
          su ubuntu
          cd ~
          echo "Hello, world!" > kek.tex
      Tags:
        - Key: Name
          Value: EC2BookAppApi
          
  SecurityGroupEC2BookAppApi:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroup_BookAppApi
      GroupDescription: Allowing SSH from everywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupEC2BookAppApi
